//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upgrade_Ingredients
    {
        public int Upg_Id { get; set; }
        public int Ing_Id { get; set; }
        public int Employee_id { get; set; }
        public Nullable<decimal> Quentity { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Total_Price { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Ingradient Ingradient { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
